camera_slider_position_controller:
  type: position_controllers/JointPositionController
  joint: camera_slider_joint
  pid:
    p: 100.0
    i: 0.01
    d: 10.0

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# PID gains for Gazebo
gazebo_ros_control:
  pid_gains:
    camera_slider_joint:
      p: 100.0
      i: 0.01
      d: 10.0